### PR TITLE
Make documentation available as a site

### PR DESCRIPTION
**Pull request by dgrammatiko**
@armenos ask @mbabker to enable the docs folder once you merge this and you will have a site similar to the custom elements for your documentation

### CODE REVIEW

**Comment by mbabker** [comment]
Umm, what am I doing?

**Comment by dgrammatiko** [comment]
@mbabker in the settings->pages: enable the docs folder:
screen shot 2017-08-22 at 21 24 16

PS: the PR needs merging before that

**Comment by mbabker** [comment]
Oh, that's easy enough.  I read "enable the docs folder" and was like "WTF", now that I know it's GitHub pages that makes sense.

**Comment by armenos** [comment]
@dgt41 What's the problem with this branch? Can you explain how I can solve this?

**Comment by dgrammatiko** [comment]
@armenos i'll do that for you

**Comment by dgrammatiko** [comment]
@armenos now it's ok

**Comment by armenos** [comment]
So it should work now? 
Where can I find the link 😊 ?

**Comment by armenos** [comment]
My docs are gone: https://github.com/joomla/accessibility/tree/master/custom-elements-docs
there are much less docs there now

**Comment by wilsonge** [comment]
This should be the URL but I think it needs some work :P  https://joomla.github.io/accessibility/#/

**Pull request merged**
